language: python
python:
  - 3.6
before_install:
  - python --version
  - pip install -U pip
  - pip install codev
script:
  - coverage run --source=com/Nicolas/ -m unittest discover;coverage report -m
  - python -m unitest discover
  